import Head from 'next/head'
import { ConnectButton } from '@rainbow-me/rainbowkit';

import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../Component/Navbar/Navbar'
import Homepage from '../Component/Home/Homepage'
import web3 from '../Blockend/web3'
import React, { useEffect, useState } from 'react';


export default function Home() {

  web3.eth.getAccounts().then(console.log);

  const [account, setAccount] = useState("");
  return (
    <div >
      <Head>
        <title>Mentor Verse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      
      <Homepage />


    </div>
  )
}
